### ISSUE TITLE
not working on Firefox?

### ISSUE THREAD

**Issue by bbonf** [UiL-OTS-labs/jspsych-vwp-webgazer#4]
Seems like it's caused by the browser optimizing the video element away. See https://github.com/brownhci/WebGazer/issues/252 and https://github.com/brownhci/WebGazer/issues/315

**Comment by bbonf** [comment]
temporary workaround is to patch `hideVideoElement` in webgazer.js

```
function hideVideoElement(val) {
  val.style.opacity = src_webgazer.params.showVideo ? '1': '0';
  val.style.display = 'block';
}
```

**Comment by jeffhuang** [comment]
Looking into this now to patch it in WebGazer directly. Thanks!
